### ISSUE TITLE
有收消息的接口吗

### ISSUE THREAD

**Issue by imapach** [anhkgg/SuperWeChatPC#10]

**Comment by anhkgg** [comment]
可以有

**Comment by zhangnew** [comment]
期待一下

**Comment by 214175590** [comment]
支持作者、谢谢作者，加油！

**Comment by madeitcwang** [comment]
支持作者

**Comment by MG0934** [comment]
期待期待，辛苦

**Comment by anhkgg** [comment]
已发布：
https://github.com/anhkgg/SuperWeChatPC/releases/tag/v1.3.0

**Comment by zhangnew** [comment]
感谢！我试了一下可以用，但是有两个问题：
1、向外发送消息也会回调接口，这个是否可以加个字段区分一下是发送还是接收信息？
2、群聊只获取的群ID，没有用户ID，不知道群里的哪个人在发言。
