### ISSUE TITLE
python 开发的话有接口提供调用么

### ISSUE THREAD

**Issue by banduoba** [anhkgg/SuperWeChatPC#14]
如题,python 开发的话有 api 接口提供么

**Comment by anhkgg** [comment]
好，后面增加

**Comment by anhkgg** [comment]
@banduoba 已经增加

**Comment by banduoba** [comment]
@anhkgg 速度啊 感谢 请问这个 python 接口说明文档哪里看啊 刚刚找了下没有看到,这个 python 接口如何调用呢

**Comment by banduoba** [comment]
看到了 不好意思

**Comment by Stone-wh** [comment]
> 看到了 不好意思

您这边python测试可以吗
