### ISSUE TITLE
在消息撤回的时候能加提示吗?

### ISSUE THREAD

**Issue by pkptzx** [anhkgg/SuperWeChatPC#20]
现在如果有人撤回了,是无法知道对方撤回这条消息的,
有时候会出大事...你懂得.
能不能加个提示?

如图,这个图是android上的微信插件防撤回的效果:

![image](https://user-images.githubusercontent.com/4339676/53789909-99210880-3f60-11e9-9bc9-448f61dde1a6.png)

祝好运.加速更新.

**Comment by anhkgg** [comment]
![revokemsg](https://user-images.githubusercontent.com/9443285/54004764-bc7eca00-4191-11e9-9cdc-6fb936b068c1.png)

**Comment by anhkgg** [comment]
https://github.com/anhkgg/SuperWeChatPC/releases/tag/v1.3.0
