### ISSUE TITLE
服务器如何调用客户端接口呢

### ISSUE THREAD

**Issue by leafzz** [anhkgg/SuperWeChatPC#21]
你好，我想收到消息之后，主动调用客户端接口，我查看了下MIDL好像不支持双向调用的吗？
要么就轮询查询但是性能不好，或者把客户端变成服务器来接收消息，还是说可以支持双向的？ 谢谢

**Comment by anhkgg** [comment]
https://github.com/anhkgg/SuperWeChatPC/releases/tag/v1.3.0
