### ISSUE TITLE
防撤回功能失效了

### ISSUE THREAD

**Issue by eden214** [anhkgg/SuperWeChatPC#27]
微信版本2.6.7.40
![QQ截图20190309202941](https://user-images.githubusercontent.com/13815955/54071643-55086d80-42aa-11e9-8677-ff11205535a5.png)

**Comment by eden214** [comment]
删了重新下又好了。。。

**Comment by eden214** [comment]
又试了几次在我公司的电脑上确实失效了，不知道为啥

**Comment by eden214** [comment]
![QQ截图20190311140026](https://user-images.githubusercontent.com/13815955/54103161-5c448e00-4406-11e9-9ebe-292ee686611b.png)

**Comment by anhkgg** [comment]
目前这个版本只支持最新2.6.7.40版本

**Comment by eden214** [comment]
哦。。。我看了一下我公司电脑的版本是2.6.7.48，难怪不行_(:з」∠)_
