### ISSUE TITLE
微信2.6.7.57双开失败。

### ISSUE THREAD

**Issue by Githubbili** [anhkgg/SuperWeChatPC#43]
最新版本的微信，更新之后双开成功之后，运行一段时间会强制退出一个。希望作者能帮忙看看。

**Comment by anhkgg** [comment]
我试了一天，两个微信正常运行

**Comment by ablebodied** [comment]
微信这新版本估计封堵了，我之前用脚本好好的，现在用脚本打开了但是无法登录，一直卡在登录界面，然后微信CPU使用率暴增，跟着就未响应了，看来还是要装旧版本才行了

**Comment by ablebodied** [comment]
![image](https://user-images.githubusercontent.com/24402121/56014948-ee072a00-5d29-11e9-9651-87cc8d14e95b.png)

**Comment by anhkgg** [comment]
@ablebodied 你的版本是多少，我官网下载最新的依然是2.6.7.57，也可以正常使用

**Comment by ablebodied** [comment]
@anhkgg 我的也是2.6.7.57，我的为啥就会这样呢？只开一个登录是完全没问题的，如果多开一个都登不上

**Comment by anhkgg** [comment]
你配置一下通用设置-文件管理的路径吧，换成非c盘的看看

**Comment by ablebodied** [comment]
@anhkgg 之前目录都这样的都好好的，应该是更新之后造成的，我其他电脑上有2.6.7.40版本的，是可以的，现在只能先用一下老版本，然后关掉检查更新了

**Comment by ablebodied** [comment]
@anhkgg 移动到非C盘居然可以了，这微信真垃圾

**Comment by Githubbili** [comment]
我现在又可以了，之前应该是我的操作问题，不好意思。

**Comment by Githubbili** [comment]
我现在又可以了，之前应该是我的操作问题，不好意思。
