### ISSUE TITLE
inject.lib 不能一起开源吗?

### ISSUE THREAD

**Issue by tick90011** [anhkgg/SuperWeChatPC#49]
现在用其他版本的vs 就没法编译通过了.  inject.lib 不能一起开源吗? 谢谢

**Comment by sman2013** [comment]
同问

由于我使用的是VS2015，刚开始编译时发现mhook版本不对，好在网上有源码，down下来后重新编译Core项目通过，但是SDK项目依赖的inject没有源码，静态库的版本不一致导致编译不过，求源码

**Comment by HsunGong** [comment]
支持一下

**Comment by zhouxinghuai** [comment]
现在用其他版本的vs 就没法编译通过了. inject.lib 不能一起开源吗? 谢谢

**Comment by huhuang03** [comment]
我搜索发现一个lib https://github.com/kubo/injector。但是没有自己试验过。

**Comment by anhkgg** [comment]
参考https://github.com/fdiskyou/injectAllTheThings
