### ISSUE TITLE
2.6.8.52 发送文本消息

### ISSUE THREAD

**Issue by huhuang03** [anhkgg/SuperWeChatPC#54]
2.6.8.52发送文本消息的call好像是 Base(WecahtWin.dll) + 0x2EB4E0

但是我注入就崩溃，我看SDK里面也没有适配2.6.8.52。
我怀疑是ecx给的值不对，我用代码注入器注入的代码为

```
push edx
push ecx
push eax

mov edx,  0x05920000
mov ecx, 0x05920040
push 1
mov eax, 0x05920034
push eax
mov eax, 0x05920020
push eax
mov eax, 0x6D7DB4E0
call eax
add esp, 0xc

pop eax
pop ecx
pop edx
```

其中0x05920000 指向0x05920004。0x05920004存储的是wxid
0x05920020指向的是0x05920024。0x05920024存储的是内容
0x05920040的内容是0

0x6D7DB4E0应该就是发送消息的call

我怀疑是ecx的值有问题。
请求大神帮我看看。。是哪里的问题。

**Comment by zhouxinghuai** [comment]
大神没空

**Comment by huhuang03** [comment]
难道是win10下代码注入器无法注入的问题?

**Comment by huhuang03** [comment]
如果编译提示无法找到 inejctDll1。可以看下是不是 设置了64位。 inject.lib使用的是32位。

**Comment by huhuang03** [comment]
这么久过去了。我已经不明白当初问问题的情况了。所以关闭掉了啊。好像问了个回答不了的问题，给的信息太模糊了。
