### ISSUE TITLE
能出一个64位版的库吗

### ISSUE THREAD

**Issue by user1203** [anhkgg/SuperWeChatPC#57]

**Comment by redreamality** [comment]
+1

**Comment by tianliang211** [comment]
+1，帮忙编译64位的dll

**Comment by anhkgg** [comment]
64位版本意义在哪？

**Comment by cncert** [comment]
> 64位版本意义在哪？

请问大佬，这个报错如何解决啊？
Traceback (most recent call last):
  File "j:/pro/wxsuper/pywx/wxxcore.py", line 69, in <module>
    wxsdk = WXSDK()
  File "j:/pro/wxsuper/pywx/wxxcore.py", line 12, in __init__
    self.sdk = ctypes.CDLL("J:/download/WeChatSDK.dll")
  File "D:\Program Files\Python36\Lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 不是有效的 Win32 应用程序。

**Comment by anhkgg** [comment]
> > 64位版本意义在哪？
> 
> 请问大佬，这个报错如何解决啊？
> Traceback (most recent call last):
> File "j:/pro/wxsuper/pywx/wxxcore.py", line 69, in 
> wxsdk = WXSDK()
> File "j:/pro/wxsuper/pywx/wxxcore.py", line 12, in **init**
> self.sdk = ctypes.CDLL("J:/download/WeChatSDK.dll")
> File "D:\Program Files\Python36\Lib\ctypes__init__.py", line 348, in **init**
> self._handle = _dlopen(self._name, mode)
> OSError: [WinError 193] %1 不是有效的 Win32 应用程序。

确认使用的32位版本py

**Comment by huzhoujoy** [comment]
求64位 +1 java报错。
Exception in thread "main" java.lang.UnsatisfiedLinkError: Unable to load library 'WeChatSDK':
%1 不是有效的 Win32 应用程序。
本地用的是64位java

**Comment by anhkgg** [comment]
微信本身是32位程序，所以没有必要提供64位的，各位使用其他语言调用的请安装一个32位版本。
