### ISSUE TITLE
Win10 Pro 1803 多开不稳定

### ISSUE THREAD

**Issue by hillwah** [anhkgg/SuperWeChatPC#6]
**System:**
Windows 10 Pro v1803

**WeChat:**
2.6.6.25

**Issue:**
1. 第一个WeChat启动原版，然后运行多开程序，多开成功后，第二个WeChat发送文件有可能崩溃退出；(此时再次运行多开程序无法多开，直接激活已登录的WeChat界面)
2. 多数情况下都无法多开，通过PE工具查看句柄
`WeChat_App_Instance_Identity_Mutex_Name`
中间的`App`
变成了随机生成的字符串
如 `WeChat_aj5r8jpxt_Instance_Identity_Mutex_Name`

**Comment by anhkgg** [comment]
感谢，由于我无法复现你的场景，我可以按你提供的信息更新一下代码，麻烦你验证一下

**Comment by hillwah** [comment]
还是不行。

**Comment by hillwah** [comment]
启动不了第二个微信。
现在启动第一个微信pe查看到的是这样。
![image](https://user-images.githubusercontent.com/2394352/50545914-605f6d00-0c59-11e9-9996-8f0ac8bb7caa.png)
