### ISSUE TITLE
python调用dll的收发消息接口报错 RPC Exception 1722/n0

### ISSUE THREAD

**Issue by venbill** [anhkgg/SuperWeChatPC#68]
微信版本2.6.7.40 和最新版本都试过了，报错：RPC Exception 1722/n0

**Comment by venbill** [comment]
最新版报错 50

**Comment by yuxuechao** [comment]
我也是这个问题，wxsdk.WXInitialize() 这个返回-1
最终报异常
RPC Exception 1722/nRPC Exception 1722/n

求解决

**Comment by venbill** [comment]
> 我也是这个问题，wxsdk.WXInitialize() 这个返回-1
> 最终报异常
> RPC Exception 1722/nRPC Exception 1722/n
> 
> 求解决

解决办法：
1.微信版本 2.6.7.40
2.安装vs2017
3.#print(wxsdk.WXSendTextMsg("wxid_n11111", "This is a python sdk test msg"))
    wxsdk.WXRecvTextMsg(g_RecvTextMsg)
先将发送消息注释了，运行接收消息拿到wxid

**Comment by Gan-Jason** [comment]
> > 我也是这个问题，wxsdk.WXInitialize() 这个返回-1
> > 最终报异常
> > RPC Exception 1722/nRPC Exception 1722/n
> > 求解决
> 
> 解决办法：
> 1.微信版本 2.6.7.40
> 2.安装vs2017
> 3.#print(wxsdk.WXSendTextMsg("wxid_n11111", "This is a python sdk test msg"))
> wxsdk.WXRecvTextMsg(g_RecvTextMsg)
> 先将发送消息注释了，运行接收消息拿到wxid

我装了vs2019，微信版本2.7.1.88，也出现这个问题，无法解决，求助
