### ISSUE TITLE
作者失踪了吗，请问为啥不更新了呢，有大神打算接吗

### ISSUE THREAD

**Issue by azz212** [anhkgg/SuperWeChatPC#74]
作者失踪了吗，请问为啥不更新了呢，有大神打算接吗

**Comment by azz212** [comment]
有交流群吗

**Comment by anhkgg** [comment]
暂时不会更新，分享了具体技术文章，如果着急可根据文章自行更新
不着急也可以关注，可能最近会更新一波
交流群有，自行找一下，谢谢
