### ISSUE TITLE
求一个微信2.6.7.40 安装包，其他版本都无法正常运行，初始化客户端失败

### ISSUE THREAD

**Issue by Gan-Jason** [anhkgg/SuperWeChatPC#82]

**Comment by Gan-Jason** [comment]
![image](https://user-images.githubusercontent.com/48959194/70401048-f3f40d00-1a68-11ea-85c2-2542bef0f638.png)


我现在微信版本是2.6.8.52，调用python接口时，各个函数返回值为图中所示，发送信息函数返回值为50

**Comment by zong400** [comment]
http://xianhezhen.tpddns.cn:81/d/file/soft/wlgj/wllt/2019-03-10/WeChat_C1012.exe

我在这里下了一个，你试下

**Comment by Gan-Jason** [comment]
> http://xianhezhen.tpddns.cn:81/d/file/soft/wlgj/wllt/2019-03-10/WeChat_C1012.exe
> 
> 我在这里下了一个，你试下

兄弟，我无法访问这个连接，显示403forbidden

**Comment by flydart** [comment]
我可以下载
