### ISSUE TITLE
Python SDK 中 的 funptr 参数有什么用处呢？

### ISSUE THREAD

**Issue by harryisfish** [anhkgg/SuperWeChatPC#86]
这个参数不知道应该怎么传？

**Comment by anhkgg** [comment]
看示例`g_RecvTextMsg = RECVTEXTMSG_CALLBACK(RecvTextMsg)`

https://github.com/anhkgg/SuperWeChatPC/blob/master/sdk/WeChatSDK.py

**Comment by CLannadZSY** [comment]
> 这个参数不知道应该怎么传？

你能发送消息给用户吗? 
我这边在初始化的时候为False, 导致后面的发送消息接口无法使用(返回结果为50), 故此来问问你, 是否遇到来同样的问题, 还是你已解决?
![image](https://user-images.githubusercontent.com/38000492/76066075-d0892180-5fc7-11ea-96b2-d5eef1d26944.png)

**Comment by harryisfish** [comment]
> > 这个参数不知道应该怎么传？
> 
> 你能发送消息给用户吗?
> 我这边在初始化的时候为False, 导致后面的发送消息接口无法使用(返回结果为50), 故此来问问你, 是否遇到来同样的问题, 还是你已解决?
> ![image](https://user-images.githubusercontent.com/38000492/76066075-d0892180-5fc7-11ea-96b2-d5eef1d26944.png)

我在 cmd 中的运行结果和你的完全一致

**Comment by CLannadZSY** [comment]
> > > 这个参数不知道应该怎么传？
> > 
> > 
> > 你能发送消息给用户吗?
> > 我这边在初始化的时候为False, 导致后面的发送消息接口无法使用(返回结果为50), 故此来问问你, 是否遇到来同样的问题, 还是你已解决?
> > ![image](https://user-images.githubusercontent.com/38000492/76066075-d0892180-5fc7-11ea-96b2-d5eef1d26944.png)
> 
> 我在 cmd 中的运行结果和你的完全一致

哈哈哈, 过于真实, 你有找到其他PC端微信的项目吗?

**Comment by harryisfish** [comment]
> > > > 这个参数不知道应该怎么传？
> > > 
> > > 
> > > 你能发送消息给用户吗?
> > > 我这边在初始化的时候为False, 导致后面的发送消息接口无法使用(返回结果为50), 故此来问问你, 是否遇到来同样的问题, 还是你已解决?
> > > ![image](https://user-images.githubusercontent.com/38000492/76066075-d0892180-5fc7-11ea-96b2-d5eef1d26944.png)
> > 
> > 
> > 我在 cmd 中的运行结果和你的完全一致
> 
> 哈哈哈, 过于真实, 你有找到其他PC端微信的项目吗?

没有哦。。。

**Comment by harryisfish** [comment]
> > > > 这个参数不知道应该怎么传？
> > > 
> > > 
> > > 你能发送消息给用户吗?
> > > 我这边在初始化的时候为False, 导致后面的发送消息接口无法使用(返回结果为50), 故此来问问你, 是否遇到来同样的问题, 还是你已解决?
> > > ![image](https://user-images.githubusercontent.com/38000492/76066075-d0892180-5fc7-11ea-96b2-d5eef1d26944.png)
> > 
> > 
> > 我在 cmd 中的运行结果和你的完全一致
> 
> 哈哈哈, 过于真实, 你有找到其他PC端微信的项目吗?

互相 follow 一下吧
